language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - libxtst-dev
            - qtdeclarative5-dev
            - libavahi-compat-libdnssd-dev
      script: sh -x ./clean_build.sh

install: true
