
  name: barrier-kvm # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  A GNU fork of Synergy. Barrier. With SSL support. Server+Client.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  barrier-kvm:
    source: https://github.com/payomagic/barrier.git
#    source-subdir: 
    # See 'snapcraft plugins'
    plugin: cmake 
    build-packages:
      - g++
      - make
      - xorg-dev 
      - libcurl4-openssl-dev
      - libavahi-compat-libdnssd-dev
      - libssl-dev
      - libx11-dev
      - libqt4-dev
      - qtbase5-dev
    stage-packages:
      - libxinerama-dev
      - libxinerama1
      - libxrandr-dev
      - libxrandr2
      - libxrender-dev
      - libxrender1
      - libxtst-dev
      - qtdeclarative5-dev
      - libavahi-compat-libdnssd-dev
      - libqt5gui5
      - qt5dxcb-plugin
    after: [qt5conf]
#     configflags:
#     - CMAKE_CXX_STANDARD 14
#     - CMAKE_CXX_EXTENSIONS OFF
apps:
  barrier-kvm:
    command: barrier
    plugs: [x11]
